#!/usr/bin/env python3
"""Compile the Motoko sweeper and embed its WASM as src/SweepWasm.mo."""
from __future__ import annotations

import pathlib
import sys

ROOT = pathlib.Path(__file__).resolve().parents[1]
WASM = ROOT / ".icp" / "cache" / "artifacts" / "sweeper"
OUT = ROOT / "src" / "SweepWasm.mo"


def _motoko_blob(data: bytes) -> str:
    return '"' + "".join(f"\\{b:02x}" for b in data) + '"'


def main() -> int:
    wasm = WASM.read_bytes() if WASM.is_file() else b""
    if not wasm:
        sys.stderr.write(f"missing {WASM} — run `icp build sweeper` first\n")
        return 1
    blob = _motoko_blob(wasm)
    OUT.write_text(
        f"""// Generated by scripts/embed_sweeper_wasm.py — do not edit by hand.
module {{
  public let wasm : Blob = {blob};
}};
"""
    )
    print(f"wrote {OUT} bytes={len(wasm)}")
    return 0


if __name__ == "__main__":
    if len(sys.argv) > 1 and sys.argv[1] == "--check":
        if not OUT.is_file():
            sys.exit("SweepWasm.mo missing")
        sys.exit(0)
    raise SystemExit(main())
