"""Asset-canister frontend bootstrap via a per-orchestra icp project."""

from __future__ import annotations

import hashlib
import os
import shutil
import subprocess

from sheetv2 import CONDUCTOR_NAMES

from casals_cli.bindings import bindings_dir
from casals_cli.multisig import ensure_control

ASSET_CANISTERS = {
    "frontend": {
        "icp_name": "casals_frontend",
        "conductor_name": CONDUCTOR_NAMES["frontend"],
        "backend": ("casals_backend", CONDUCTOR_NAMES["backend"]),
        "dist_rel": "dist",
        "build_cmd": (
            ["npm", "--prefix", "frontend", "ci"],
            ["npm", "--prefix", "frontend", "run", "build"],
        ),
    },
    "file_registry_frontend": {
        "icp_name": "ic_file_registry_frontend",
        "conductor_name": CONDUCTOR_NAMES["file_registry_frontend"],
        "backend": ("ic_file_registry", CONDUCTOR_NAMES["file_registry"]),
        "dist_rel": "file_registry_dist",
        "build_cmd": (["make", "build-registry-frontend"],),
    },
}

def icp_project_dir(sheet_name: str, env: str) -> str:
    safe = sheet_name.replace("/", "_")
    return os.path.join(bindings_dir(), "projects", f"{safe}.{env}")


def dir_content_hash(path: str) -> str:
    """SHA-256 over relative paths + file bytes (sorted for stability)."""
    if not os.path.isdir(path):
        raise FileNotFoundError(f"asset directory not found: {path}")
    digest = hashlib.sha256()
    for root, dirs, files in os.walk(path):
        dirs.sort()
        for name in sorted(files):
            fp = os.path.join(root, name)
            rel = os.path.relpath(fp, path).replace(os.sep, "/")
            digest.update(rel.encode("utf-8"))
            digest.update(b"\0")
            with open(fp, "rb") as f:
                while True:
                    chunk = f.read(65536)
                    if not chunk:
                        break
                    digest.update(chunk)
    return digest.hexdigest()


def ensure_asset_build(key: str, project_root: str, progress=None) -> str:
    """Build frontend assets if missing; return absolute dist path."""
    spec = ASSET_CANISTERS[key]
    dist_path = os.path.join(project_root, spec["dist_rel"])
    if os.path.isdir(dist_path) and os.listdir(dist_path):
        return os.path.abspath(dist_path)
    if progress:
        progress(f"  building {spec['dist_rel']}…")
    for cmd in spec["build_cmd"]:
        result = subprocess.run(cmd, cwd=project_root, capture_output=True, text=True, timeout=900)
        if result.returncode != 0:
            raise RuntimeError(
                f"{' '.join(cmd)} failed:\nstdout: {result.stdout[-800:]}\nstderr: {result.stderr[-800:]}"
            )
    if not os.path.isdir(dist_path):
        raise FileNotFoundError(f"expected build output at {dist_path}")
    return os.path.abspath(dist_path)


def write_icp_project(
    project_dir: str, casals_dist: str, registry_dist: str, env: str, network_url: str, conductor_ids: dict[str, str]
) -> None:
    """Write icp.yaml for the two asset canisters (no build steps).

    The project declares environment ``env`` as *connected* to ``network_url`` so
    `icp deploy` talks to the same replica/mainnet the rest of `casals up` uses.
    The asset sync plugin only accepts relative, symlink-free dirs, so each dist
    is copied into the project directory. Each UI finds its backend through the
    `ic_env` cookie, which the asset canister builds at install time from the
    `PUBLIC_CANISTER_ID:*` environment variables declared here.
    """
    os.makedirs(project_dir, exist_ok=True)
    for sub in ("cache", "data"):  # icp-cli `link --force` fails if these are missing
        os.makedirs(os.path.join(project_dir, ".icp", sub, "mappings"), exist_ok=True)
    for link_name, target in (("casals_frontend_dist", casals_dist), ("ic_file_registry_frontend_dist", registry_dist)):
        dest = os.path.join(project_dir, link_name)
        shutil.rmtree(dest, ignore_errors=True)
        shutil.copytree(target, dest)
    root_key = "mainnet" if env == "ic" else "fetch"
    settings = ""
    for spec in ASSET_CANISTERS.values():
        icp_backend, conductor_backend = spec["backend"]
        backend_id = conductor_ids.get(conductor_backend, "")
        if backend_id:
            settings += f"""      {spec["icp_name"]}:
        environment_variables:
          "PUBLIC_CANISTER_ID:{icp_backend}": {backend_id}
"""
    content = f"""# Generated by casals up — private icp project for one orchestra
networks:
  - name: {env}
    mode: connected
    url: {network_url}
    root-key: {root_key}

environments:
  - name: {env}
    network: {env}
    settings:
{settings}
canisters:
  - name: casals_frontend
    recipe:
      type: "@dfinity/asset-canister@v2.2.0"
      configuration:
        dir: casals_frontend_dist

  - name: ic_file_registry_frontend
    recipe:
      type: "@dfinity/asset-canister@v2.2.0"
      configuration:
        dir: ic_file_registry_frontend_dist
"""
    path = os.path.join(project_dir, "icp.yaml")
    with open(path, "w", encoding="utf-8") as f:
        f.write(content)


def bootstrap_asset_canister(
    ic,
    bindings,
    *,
    key: str,
    project_dir: str,
    dist_path: str,
    deployer: str,
    multisig_id: str = "",
    progress=None,
) -> None:
    """Link detached id → deploy asset wasm + sync; idempotent on unchanged dist."""
    spec = ASSET_CANISTERS[key]
    icp_name = spec["icp_name"]
    conductor_name = spec["conductor_name"]
    dist_hash = dir_content_hash(dist_path)
    stored_dist_hash = bindings.asset_dist_hashes.get(icp_name, "")
    existing_id = bindings.conductor.get(conductor_name, "")
    stored_module_hash = bindings.conductor_module_hashes.get(conductor_name, "")

    live_hash = ic.read_module_hash(existing_id) if existing_id else None
    if existing_id and live_hash is None and not ic.canister_exists(existing_id):
        if progress:
            progress(f"  {conductor_name}: {existing_id} is not on this network; creating anew")
        existing_id = ""
    has_live_module = live_hash is not None

    if existing_id and has_live_module and stored_module_hash:
        if live_hash.lower() != stored_module_hash.lower():
            if progress:
                progress(f"  {conductor_name}: module hash drift, redeploying assets")
            ensure_control(ic, existing_id, deployer, multisig_id)
            ic.icp_project(project_dir, ["canister", "link", icp_name, existing_id, "--force"])
            ic.icp_project(
                project_dir,
                ["deploy", icp_name, "--no-create", "--mode", "upgrade", "-y"],
                timeout=900,
            )
            live_hash = ic.read_module_hash(existing_id)
            if live_hash:
                bindings.conductor_module_hashes[conductor_name] = live_hash
            bindings.asset_dist_hashes[icp_name] = dist_hash
            bindings.save()
            return
        elif dist_hash == stored_dist_hash:
            if progress:
                progress(f"  {conductor_name}: {existing_id} (skip — dist unchanged)")
            return
        else:
            if progress:
                progress(f"  {conductor_name}: syncing assets (dist changed)")
            ensure_control(ic, existing_id, deployer, multisig_id)
            ic.icp_project(project_dir, ["sync", icp_name], timeout=900)
            bindings.asset_dist_hashes[icp_name] = dist_hash
            bindings.save()
            return

    if existing_id and has_live_module and not stored_module_hash:
        bindings.conductor_module_hashes[conductor_name] = live_hash or ""
        if dist_hash != stored_dist_hash:
            if progress:
                progress(f"  {conductor_name}: syncing assets (dist changed)")
            ensure_control(ic, existing_id, deployer, multisig_id)
            ic.icp_project(project_dir, ["sync", icp_name], timeout=900)
        elif progress:
            progress(f"  {conductor_name}: {existing_id} (recorded module hash)")
        bindings.asset_dist_hashes[icp_name] = dist_hash
        bindings.save()
        return

    if progress:
        progress(f"  {conductor_name}: create + deploy assets")
    cid = existing_id or ic.create_detached()
    bindings.conductor[conductor_name] = cid
    bindings.save()  # persist before install: a failure later must not orphan the canister
    ic.settings_update(cid, set_controllers=[deployer])
    ic.icp_project(project_dir, ["canister", "link", icp_name, cid, "--force"])
    ic.icp_project(
        project_dir,
        ["deploy", icp_name, "--no-create", "--mode", "install", "-y"],
        timeout=900,
    )
    live_hash = ic.read_module_hash(cid)
    bindings.conductor[conductor_name] = cid
    if live_hash:
        bindings.conductor_module_hashes[conductor_name] = live_hash
    bindings.asset_dist_hashes[icp_name] = dist_hash
    bindings.save()
