"""Asset-canister frontend bootstrap via a per-orchestra icp project."""

from __future__ import annotations

import hashlib
import os
import subprocess

from sheetv2 import CONDUCTOR_NAMES

ASSET_CANISTERS = {
    "frontend": {
        "icp_name": "casals_frontend",
        "conductor_name": CONDUCTOR_NAMES["frontend"],
        "dist_rel": "dist",
        "build_cmd": (
            ["npm", "--prefix", "frontend", "ci"],
            ["npm", "--prefix", "frontend", "run", "build"],
        ),
    },
    "file_registry_frontend": {
        "icp_name": "ic_file_registry_frontend",
        "conductor_name": CONDUCTOR_NAMES["file_registry_frontend"],
        "dist_rel": "file_registry_dist",
        "build_cmd": (["make", "build-registry-frontend"],),
    },
}

PROJECTS_DIR = os.path.join(os.path.expanduser("~/.casals"), "projects")


def icp_project_dir(sheet_name: str, env: str) -> str:
    safe = sheet_name.replace("/", "_")
    return os.path.join(PROJECTS_DIR, f"{safe}.{env}")


def dir_content_hash(path: str) -> str:
    """SHA-256 over relative paths + file bytes (sorted for stability)."""
    if not os.path.isdir(path):
        raise FileNotFoundError(f"asset directory not found: {path}")
    digest = hashlib.sha256()
    for root, dirs, files in os.walk(path):
        dirs.sort()
        for name in sorted(files):
            fp = os.path.join(root, name)
            rel = os.path.relpath(fp, path).replace(os.sep, "/")
            digest.update(rel.encode("utf-8"))
            digest.update(b"\0")
            with open(fp, "rb") as f:
                while True:
                    chunk = f.read(65536)
                    if not chunk:
                        break
                    digest.update(chunk)
    return digest.hexdigest()


def ensure_asset_build(key: str, project_root: str, progress=None) -> str:
    """Build frontend assets if missing; return absolute dist path."""
    spec = ASSET_CANISTERS[key]
    dist_path = os.path.join(project_root, spec["dist_rel"])
    if os.path.isdir(dist_path) and os.listdir(dist_path):
        return os.path.abspath(dist_path)
    if progress:
        progress(f"  building {spec['dist_rel']}…")
    for cmd in spec["build_cmd"]:
        result = subprocess.run(cmd, cwd=project_root, capture_output=True, text=True, timeout=900)
        if result.returncode != 0:
            raise RuntimeError(
                f"{' '.join(cmd)} failed:\nstdout: {result.stdout[-800:]}\nstderr: {result.stderr[-800:]}"
            )
    if not os.path.isdir(dist_path):
        raise FileNotFoundError(f"expected build output at {dist_path}")
    return os.path.abspath(dist_path)


def write_icp_project(project_dir: str, casals_dist: str, registry_dist: str) -> None:
    """Write icp.yaml for the two asset canisters (absolute dirs, no build steps)."""
    os.makedirs(project_dir, exist_ok=True)
    content = f"""# Generated by casals up — private icp project for one orchestra
canisters:
  - name: casals_frontend
    recipe:
      type: "@dfinity/asset-canister@v2.2.0"
      configuration:
        dir: {casals_dist}

  - name: ic_file_registry_frontend
    recipe:
      type: "@dfinity/asset-canister@v2.2.0"
      configuration:
        dir: {registry_dist}
"""
    path = os.path.join(project_dir, "icp.yaml")
    with open(path, "w", encoding="utf-8") as f:
        f.write(content)


def bootstrap_asset_canister(
    ic,
    bindings,
    *,
    key: str,
    project_dir: str,
    dist_path: str,
    deployer: str,
    progress=None,
) -> None:
    """Link detached id → deploy asset wasm + sync; idempotent on unchanged dist."""
    spec = ASSET_CANISTERS[key]
    icp_name = spec["icp_name"]
    conductor_name = spec["conductor_name"]
    dist_hash = dir_content_hash(dist_path)
    stored_dist_hash = bindings.asset_dist_hashes.get(icp_name, "")
    existing_id = bindings.conductor.get(conductor_name, "")
    stored_module_hash = bindings.conductor_module_hashes.get(conductor_name, "")

    live_hash = ic.read_module_hash(existing_id) if existing_id else None
    has_live_module = live_hash is not None

    if existing_id and has_live_module and stored_module_hash:
        if live_hash.lower() != stored_module_hash.lower():
            if progress:
                progress(f"  {conductor_name}: module hash drift, redeploying assets")
            ic.icp_project(project_dir, ["canister", "link", icp_name, existing_id, "--force"])
            ic.icp_project(
                project_dir,
                ["deploy", icp_name, "--no-create", "--mode", "upgrade", "-y"],
                timeout=900,
            )
            live_hash = ic.read_module_hash(existing_id)
            if live_hash:
                bindings.conductor_module_hashes[conductor_name] = live_hash
            bindings.asset_dist_hashes[icp_name] = dist_hash
            bindings.save()
            return
        elif dist_hash == stored_dist_hash:
            if progress:
                progress(f"  {conductor_name}: {existing_id} (skip — dist unchanged)")
            return
        else:
            if progress:
                progress(f"  {conductor_name}: syncing assets (dist changed)")
            ic.icp_project(project_dir, ["sync", icp_name], timeout=900)
            bindings.asset_dist_hashes[icp_name] = dist_hash
            bindings.save()
            return

    if existing_id and has_live_module and not stored_module_hash:
        bindings.conductor_module_hashes[conductor_name] = live_hash or ""
        if dist_hash != stored_dist_hash:
            if progress:
                progress(f"  {conductor_name}: syncing assets (dist changed)")
            ic.icp_project(project_dir, ["sync", icp_name], timeout=900)
        elif progress:
            progress(f"  {conductor_name}: {existing_id} (recorded module hash)")
        bindings.asset_dist_hashes[icp_name] = dist_hash
        bindings.save()
        return

    if progress:
        progress(f"  {conductor_name}: create + deploy assets")
    cid = existing_id or ic.create_detached()
    ic.settings_update(cid, set_controllers=[deployer])
    ic.icp_project(project_dir, ["canister", "link", icp_name, cid, "--force"])
    ic.icp_project(
        project_dir,
        ["deploy", icp_name, "--no-create", "--mode", "install", "-y"],
        timeout=900,
    )
    live_hash = ic.read_module_hash(cid)
    bindings.conductor[conductor_name] = cid
    if live_hash:
        bindings.conductor_module_hashes[conductor_name] = live_hash
    bindings.asset_dist_hashes[icp_name] = dist_hash
    bindings.save()
