"""One laptop, many local replicas.

icp binds one gateway per project (`gateway.port` in that project's icp.yaml).
Casals used to assume the implicit `local` network on :8000 in the repo
checkout, so a second `casals up` stole CPU (and `icp network stop` killed
the first replica).

Isolation is opt-in via env (CI and a lone `local_up` stay on :8000):

    CASALS_REPLICA=1              # isolate; pick a free port ≥ 8001
    CASALS_REPLICA_PORT=auto      # same
    CASALS_REPLICA_PORT=8001      # isolate on that port
    CASALS_REPLICA_HOME=/path     # icp project + replica state (default
                                  # $CASALS_HOME/.replica when isolating)

`activate()` writes the project, exports the env vars for child processes,
and is a no-op when none of the knobs above are set.
"""

from __future__ import annotations

import os
import socket
import subprocess
import sys
from dataclasses import dataclass
from urllib.parse import urlparse

from casals_cli.util import run_icp_cmd

DEFAULT_PORT = 8000
DEFAULT_URL = f"http://127.0.0.1:{DEFAULT_PORT}"
PORT_RANGE = range(8001, 8100)


@dataclass(frozen=True)
class Replica:
    home: str | None
    port: int
    url: str
    isolated: bool


def port_in_use(port: int, host: str = "127.0.0.1") -> bool:
    try:
        with socket.create_connection((host, port), timeout=0.3):
            return True
    except OSError:
        return False


def pick_free_port(host: str = "127.0.0.1") -> int:
    for port in PORT_RANGE:
        with socket.socket(socket.AF_INET, socket.SOCK_STREAM) as sock:
            sock.setsockopt(socket.SOL_SOCKET, socket.SO_REUSEADDR, 1)
            try:
                sock.bind((host, port))
            except OSError:
                continue
            return port
    raise RuntimeError(f"no free replica port in {PORT_RANGE.start}-{PORT_RANGE.stop - 1}")


def port_from_url(url: str | None) -> int:
    if not url:
        return DEFAULT_PORT
    parsed = urlparse(url)
    if parsed.port:
        return parsed.port
    return 443 if parsed.scheme == "https" else DEFAULT_PORT


def isolating() -> bool:
    port = (os.environ.get("CASALS_REPLICA_PORT") or "").strip()
    home = (os.environ.get("CASALS_REPLICA_HOME") or "").strip()
    flag = (os.environ.get("CASALS_REPLICA") or "").strip().lower()
    if home:
        return True
    if port and port != str(DEFAULT_PORT):
        return True
    return flag in ("1", "true", "yes", "auto")


def replica_home() -> str | None:
    home = (os.environ.get("CASALS_REPLICA_HOME") or "").strip()
    if home:
        return os.path.abspath(home)
    if not isolating():
        return None
    root = (os.environ.get("CASALS_HOME") or "").strip() or os.path.join(
        os.path.expanduser("~"), "casals-home"
    )
    return os.path.abspath(os.path.join(root, ".replica"))


def network_url() -> str:
    explicit = (os.environ.get("CASALS_NETWORK_URL") or "").strip()
    if explicit:
        return explicit.rstrip("/")
    port = (os.environ.get("CASALS_REPLICA_PORT") or "").strip()
    if port.isdigit():
        return f"http://127.0.0.1:{port}"
    return DEFAULT_URL


def canister_http_url(cid: str, path: str = "/", *, url: str | None = None) -> str:
    """Browser / oracle URL for a canister on this replica's gateway."""
    port = port_from_url(url or network_url())
    if not path.startswith("/"):
        path = "/" + path
    return f"http://{cid}.localhost:{port}{path}"


def write_replica_project(home: str, port: int) -> str:
    """Write a managed `local` network that owns `port`. Returns the yaml path."""
    os.makedirs(os.path.join(home, ".icp", "cache", "mappings"), exist_ok=True)
    os.makedirs(os.path.join(home, ".icp", "data", "mappings"), exist_ok=True)
    path = os.path.join(home, "icp.yaml")
    path_tmp = path + ".tmp"
    with open(path_tmp, "w", encoding="utf-8") as fh:
        fh.write(
            "# Generated by casals_cli.replica — one isolated local replica.\n"
            "# Do not point other runs at this directory.\n"
            "networks:\n"
            "  - name: local\n"
            "    mode: managed\n"
            "    gateway:\n"
            "      bind: 127.0.0.1\n"
            f"      port: {int(port)}\n"
            "environments:\n"
            "  - name: local\n"
            "    network: local\n"
        )
    os.replace(path_tmp, path)
    return path


def write_env_file(home: str, port: int, url: str) -> str:
    path = os.path.join(home, "env")
    with open(path, "w", encoding="utf-8") as fh:
        fh.write(f"CASALS_REPLICA_HOME={home}\n")
        fh.write(f"CASALS_REPLICA_PORT={port}\n")
        fh.write(f"CASALS_NETWORK_URL={url}\n")
    return path


def recorded_port(home: str) -> int | None:
    """The port the last `activate` wrote to `<home>/env`, if any."""
    path = os.path.join(home, "env")
    if not os.path.isfile(path):
        return None
    with open(path, encoding="utf-8") as fh:
        for line in fh:
            key, _, value = line.strip().partition("=")
            if key == "CASALS_REPLICA_PORT" and value.strip().isdigit():
                return int(value.strip())
    return None


def export_env(replica: Replica) -> None:
    if replica.home:
        os.environ["CASALS_REPLICA_HOME"] = replica.home
    os.environ["CASALS_REPLICA_PORT"] = str(replica.port)
    os.environ["CASALS_NETWORK_URL"] = replica.url


def icp_project_args() -> list[str]:
    home = replica_home()
    if home and os.path.isfile(os.path.join(home, "icp.yaml")):
        return ["--project-root-override", home]
    return []


def activate() -> Replica:
    """Resolve isolation, write the sidecar project, export env. Does not start icp."""
    if not isolating():
        replica = Replica(home=None, port=DEFAULT_PORT, url=DEFAULT_URL, isolated=False)
        return replica

    home = replica_home()
    assert home is not None
    os.makedirs(home, exist_ok=True)
    port_spec = (os.environ.get("CASALS_REPLICA_PORT") or "").strip().lower()
    if port_spec in ("", "auto", "0"):
        # A replica this home already runs (KEEP=1, or a previous run still up)
        # is reused; picking another free port would rewrite the sidecar
        # project to a port nothing listens on.
        recorded = recorded_port(home)
        port = recorded if recorded and port_in_use(recorded) else pick_free_port()
    else:
        port = int(port_spec)
    url = f"http://127.0.0.1:{port}"
    write_replica_project(home, port)
    write_env_file(home, port, url)
    replica = Replica(home=home, port=port, url=url, isolated=True)
    export_env(replica)
    return replica


def _icp(argv: list[str], *, timeout: int = 300) -> subprocess.CompletedProcess[str]:
    cmd = ["icp", *argv, *icp_project_args()]
    cwd = replica_home() or os.getcwd()
    return run_icp_cmd(cmd, cwd=cwd, capture_output=True, text=True, timeout=timeout)


def status_ok() -> bool:
    return _icp(["network", "status", "-e", "local"], timeout=30).returncode == 0


def healthy(replica: Replica) -> bool:
    """Running *and* answering on the port the sidecar names. icp tracks a
    managed network by project, so `network status` alone stays green after the
    sidecar was rewritten for another port."""
    return status_ok() and (not replica.isolated or port_in_use(replica.port))


def start(replica: Replica | None = None) -> Replica:
    """Start this replica if needed. Returns the (possibly newly activated) replica."""
    replica = replica or activate()
    if healthy(replica):
        return replica
    if status_ok():
        # running for another port: restart it on this one
        _icp(["network", "stop", "-e", "local"], timeout=120)
    extra = ["--project-root-override", replica.home] if replica.home else []
    cwd = replica.home or os.getcwd()
    res = run_icp_cmd(
        ["icp", "network", "start", "-e", "local", "--background", *extra],
        cwd=cwd,
        capture_output=True,
        text=True,
        timeout=300,
    )
    if res.returncode != 0 and not status_ok():
        raise RuntimeError(
            f"icp network start failed (port {replica.port}):\n"
            f"{(res.stderr or res.stdout)[-1500:]}"
        )
    for _ in range(60):
        if healthy(replica):
            return replica
        import time

        time.sleep(1)
    raise RuntimeError(f"replica on {replica.url} did not come up")


def stop(replica: Replica | None = None) -> None:
    replica = replica or activate()
    extra = ["--project-root-override", replica.home] if replica.home else []
    cwd = replica.home or os.getcwd()
    run_icp_cmd(
        ["icp", "network", "stop", "-e", "local", *extra],
        cwd=cwd,
        capture_output=True,
        text=True,
        timeout=120,
    )


def _print_exports(replica: Replica) -> None:
    print(f"export CASALS_REPLICA_PORT={replica.port}")
    print(f"export CASALS_NETWORK_URL={replica.url}")
    if replica.home:
        print(f"export CASALS_REPLICA_HOME={replica.home}")


def main(argv: list[str] | None = None) -> int:
    args = list(sys.argv[1:] if argv is None else argv)
    cmd = args[0] if args else "env"
    if cmd in ("-h", "--help"):
        print("usage: python3 -m casals_cli.replica [env|start|stop|status]")
        return 0
    if cmd == "env":
        _print_exports(activate())
        return 0
    if cmd == "start":
        replica = start()
        print(f"replica {replica.url} isolated={replica.isolated} home={replica.home or '-'}", file=sys.stderr)
        _print_exports(replica)
        return 0
    if cmd == "stop":
        stop()
        return 0
    if cmd == "status":
        replica = activate()
        ok = status_ok()
        print(f"{'up' if ok else 'down'} {replica.url} isolated={replica.isolated}")
        return 0 if ok else 1
    print(f"unknown command: {cmd}", file=sys.stderr)
    return 2


if __name__ == "__main__":
    sys.exit(main())
